# Generated by Django 2.1.4 on 2018-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64, null=True, unique=True)),
                ('username', models.CharField(max_length=64, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('level', models.CharField(choices=[('Admin', 'Admin'), ('Normal', 'Normal')], default='Admin', max_length=32)),
            ],
            options={
                'db_table': 'USERS',
                'ordering': ['-id'],
            },
        ),
    ]
