DROP TABLE IF EXISTS videos;

CREATE TABLE videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(50) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description TEXT NOT NULL,
  imdb_rating FLOAT NOT NULL,
  thumbnail_path TEXT NOT NULL,
  video_path TEXT NOT NULL
);
