version: '3'

services:
  wishlist:
    build: ./Wishlist
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  user:
    build: ./User
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"  
  catalogue:
    build: ./Catalogue
    command: python3 manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"