version: '3'

services:
  wishlist:
    build: ./Wishlist
    command: python3 manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/wish
      - ./Wishlist/db.sqlite3:/code/db.sqlite3:rw
    ports:
      - "8000:8000"
  user:
    build: ./User
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/user
      - ./User/db.sqlite3:/code/db.sqlite3:rw
    ports:
      - "8001:8001"  
  catalogue:
    build: ./Catalogue
    command: python3 manage.py runserver 0.0.0.0:8002 
    volumes:
      - .:/catalogue
      - ./Catalogue/db.sqlite3:/code/db.sqlite3:rw
    ports:
      - "8002:8002"
#  frontend:
#    build: ./frontend
#    command: npm run serve 
#    volumes:
#      - .:/frontend
#    ports:
#      - "8080:8080"
#    depends:
#      - wishlist
