version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672 # port for the daemon API
      - 15672:15672 # port for the RabbitMQ management interface
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

  wishlist:
    build: ./Wishlist
    command: python3 manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/wish
    ports:
      - "8000:8000"
  user:
    build: ./User
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/user
    ports:
      - "8001:8001"  
  catalogue:
    build: ./Catalogue
    command: python3 manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/catalogue
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq

  videostream:
    build: ./VideoStream
    command: python main.py 
    volumes:
      - .:/videostream
      - ./VideoStream/db/videos.sqlite:/code/db/videos.sqlite:rw
      - ./VideoStream/videos:/code/videos
    ports:
      - "8005:8005"

  consumer-service:
    build: ./consumer-service
    command: python consumer.py
    restart: always
    depends_on:
      - rabbitmq

      
  frontend:
    build: ./frontend
    command: npm run serve 
    volumes:
      - .:/frontend
    ports:
      - "8080:8080"
    depends_on:
      - wishlist
