# Generated by Django 2.1.4 on 2019-01-13 15:13

import catalogue.models.catalogue
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('year', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalogue.models.catalogue.get_image_path)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'CATALOGUE',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'CATEGORY',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalogue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Catalogue')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
            options={
                'db_table': 'VIDEO_TO_CATEGORY',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ManyToManyField(null=True, to='catalogue.Category'),
        ),
    ]
