# Generated by Django 2.1.4 on 2018-12-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('image_path', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'CATALOGUE',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'CATEGORY    ',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ManyToManyField(to='catalogue.Category'),
        ),
    ]
