# Generated by Django 2.1.4 on 2019-01-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocategory',
            name='catalogue_id',
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
    ]
