# Generated by Django 2.1.4 on 2018-12-05 10:59

import catalogue.models.catalogue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_catalogue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalogue.models.catalogue.get_image_path),
        ),
    ]
