# Generated by Django 2.1.4 on 2018-12-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20181205_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='image_path',
        ),
    ]
