# Generated by Django 2.1.4 on 2018-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_catalogue_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
