# Generated by Django 2.1.4 on 2018-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20181205_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
