# Generated by Django 2.1.4 on 2018-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Wishes',
                'ordering': ['-id'],
            },
        ),
    ]
