# Generated by Django 2.1.4 on 2019-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='user_email',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
